const STORAGE_KEY="finanzas_familiares_v31_premium";
const LEGACY_KEYS=["finanzas_familiares_v2_bonita","finanzas_familiares_v3_elegante","finanzas_familiares_v3","finanzas_familiares_v2","finanzas_familiares_v1"];
const OWNERS=["Alexander","Nuri","Hogar"];
const CATEGORIES=["Mercado","Servicios","Transporte","Salud","Educación","Ahorro","Entretenimiento","Arriendo","Cuotas","Deudas","Regalos","Otros"];
const state=loadData();
const $=id=>document.getElementById(id);
const formatMoney=n=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(n)||0);
function defaultState(){return{goals:{monthly:0,total:0},budgets:[],transactions:[],savedAt:null};}
function normalize(data){const base=defaultState();return{goals:{...base.goals,...(data.goals||{})},budgets:Array.isArray(data.budgets)?data.budgets:[],transactions:Array.isArray(data.transactions)?data.transactions:[],savedAt:data.savedAt||null};}
function loadData(){try{const current=localStorage.getItem(STORAGE_KEY);if(current)return normalize(JSON.parse(current));for(const key of LEGACY_KEYS){const legacy=localStorage.getItem(key);if(legacy){const parsed=normalize(JSON.parse(legacy));saveData(parsed);return parsed;}}}catch(e){console.error(e);}return defaultState();}
function saveData(next=state){next.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state.goals=next.goals;state.budgets=next.budgets;state.transactions=next.transactions;state.savedAt=next.savedAt;render();}
function sum(list){return list.reduce((a,b)=>a+(Number(b)||0),0);}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
function populateSelects(){[$("txCategory"),$("budgetCategory")].forEach(select=>{select.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join("");});$("txDate").value=new Date().toISOString().slice(0,10);}
function setTabs(){document.querySelectorAll(".tab").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const tab=btn.dataset.tab;document.querySelectorAll(".tab-content").forEach(s=>s.classList.add("hidden"));$("tab-"+tab).classList.remove("hidden");});});}
function setupEvents(){
  $("btnSaveGoals").addEventListener("click",()=>{state.goals.monthly=Number($("goalMonthly").value||0);state.goals.total=Number($("goalTotal").value||0);saveData(state);});
  $("btnSaveTx").addEventListener("click",saveTransaction);$("btnClearTx").addEventListener("click",clearTransactionForm);
  $("btnSaveBudget").addEventListener("click",()=>{const category=$("budgetCategory").value;const amount=Number($("budgetAmount").value||0);if(!category||amount<=0)return alert("Ingresa una categoría y un monto válido.");const existing=state.budgets.find(b=>b.category===category);if(existing)existing.amount=amount;else state.budgets.push({id:uid(),category,amount});$("budgetAmount").value="";saveData(state);});
  $("filterOwner").addEventListener("change",renderTransactions);$("filterType").addEventListener("change",renderTransactions);
  $("btnBackup").addEventListener("click",exportBackup);$("btnImport").addEventListener("click",()=>$("fileImport").click());$("fileImport").addEventListener("change",importBackup);$("btnExcel").addEventListener("click",exportCSV);
  $("btnReset").addEventListener("click",()=>{if(confirm("Esto reiniciará la app localmente. ¿Continuar?")){saveData(defaultState());clearTransactionForm();}});
}
function saveTransaction(){
  const tx={id:uid(),type:$("txType").value,owner:$("txOwner").value,date:$("txDate").value||new Date().toISOString().slice(0,10),category:$("txCategory").value,amount:Number($("txAmount").value||0),method:$("txMethod").value,description:$("txDescription").value.trim(),note:$("txNote").value.trim(),split:$("txSplit").value,debtStatus:$("txDebtStatus").value};
  if(!tx.amount||tx.amount<=0||!tx.description)return alert("Completa al menos valor y descripción.");
  if(tx.type==="gasto"&&tx.split==="si"){const half=Math.round(tx.amount/2), other=tx.amount-half;state.transactions.push({...tx,id:uid(),owner:"Alexander",amount:half,description:tx.description+" (50/50)",split:"si"},{...tx,id:uid(),owner:"Nuri",amount:other,description:tx.description+" (50/50)",split:"si"});}
  else state.transactions.push(tx);
  clearTransactionForm();saveData(state);
}
function clearTransactionForm(){$("txType").value="ingreso";$("txOwner").value="Alexander";$("txDate").value=new Date().toISOString().slice(0,10);$("txCategory").value=CATEGORIES[0];$("txAmount").value="";$("txMethod").value="Efectivo";$("txDescription").value="";$("txNote").value="";$("txSplit").value="no";$("txDebtStatus").value="pendiente";}
function getTotals(){const income=sum(state.transactions.filter(t=>t.type==="ingreso").map(t=>t.amount));const expense=sum(state.transactions.filter(t=>t.type==="gasto").map(t=>t.amount));const debt=sum(state.transactions.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));return{income,expense,debt,balance:income-expense-debt};}
function byOwner(owner){const rows=state.transactions.filter(t=>t.owner===owner);const income=sum(rows.filter(t=>t.type==="ingreso").map(t=>t.amount));const expense=sum(rows.filter(t=>t.type==="gasto").map(t=>t.amount));const debt=sum(rows.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));return{income,expense,debt,balance:income-expense-debt};}
function currentMonthRows(){const ym=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>(t.date||"").slice(0,7)===ym);}
function expenseByCategory(rows=state.transactions){const map={};rows.filter(t=>t.type==="gasto"||t.type==="deuda").forEach(t=>map[t.category]=(map[t.category]||0)+Number(t.amount||0));return Object.entries(map).map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);}
function buildMonthSummary(income,expense,debt,balance){if(!currentMonthRows().length)return "Todavía no hay suficientes movimientos para el cierre mensual.";return balance>=0?`Este mes cerraron con saldo positivo de ${formatMoney(balance)}. Van por buen camino.`:`Este mes cerraron con un faltante de ${formatMoney(Math.abs(balance))}. Conviene ajustar algunos gastos.`;}
function buildMonthInsight(rows){if(!rows.length)return "Empiecen registrando movimientos para ver recomendaciones.";const active=OWNERS.map(o=>({owner:o,total:sum(rows.filter(t=>t.owner===o).map(t=>t.amount))})).sort((a,b)=>b.total-a.total)[0];const top=expenseByCategory(rows)[0];return top?`La cuenta más activa fue ${active.owner} y la categoría dominante fue ${top.category}.`:`La cuenta más activa fue ${active.owner}.`;}
function getBudgetAlerts(){const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));return state.budgets.map(b=>{const spent=monthMap[b.category]||0;const percent=b.amount?Math.round((spent/b.amount)*100):0;return{category:b.category,spent,limit:b.amount,percent};}).filter(a=>a.percent>=80).sort((a,b)=>b.percent-a.percent);}
function buildBudgetInfo(rows){if(!rows.length)return "Aún no hay datos para comparar.";const alerts=getBudgetAlerts();if(!alerts.length)return "Van dentro del presupuesto en las categorías configuradas.";const worst=alerts[0];return `La categoría ${worst.category} va en ${worst.percent}% del presupuesto mensual.`;}
function renderDashboard(){
  const totals=getTotals();$("metricBalance").textContent=formatMoney(totals.balance);$("metricIncome").textContent=formatMoney(totals.income);$("metricExpense").textContent=formatMoney(totals.expense);$("metricDebt").textContent=formatMoney(totals.debt);
  OWNERS.forEach(owner=>{const key=owner==="Hogar"?"Hogar":owner;const data=byOwner(owner);$("sum"+key+"Income").textContent=formatMoney(data.income);$("sum"+key+"Expense").textContent=formatMoney(data.expense);$("sum"+key+"Debt").textContent=formatMoney(data.debt);$("sum"+key+"Balance").textContent=formatMoney(data.balance);});
  const monthRows=currentMonthRows();const monthIncome=sum(monthRows.filter(t=>t.type==="ingreso").map(t=>t.amount));const monthExpense=sum(monthRows.filter(t=>t.type==="gasto").map(t=>t.amount));const monthDebt=sum(monthRows.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));const monthBalance=monthIncome-monthExpense-monthDebt;
  $("monthIncome").textContent=formatMoney(monthIncome);$("monthExpense").textContent=formatMoney(monthExpense+monthDebt);$("monthBalance").textContent=formatMoney(monthBalance);
  const monthGoal=Number(state.goals.monthly||0), totalGoal=Number(state.goals.total||0), monthSave=Math.max(0,monthBalance), totalSave=Math.max(0,totals.balance);
  const monthPct=monthGoal>0?Math.min(100,Math.round((monthSave/monthGoal)*100)):0;const totalPct=totalGoal>0?Math.min(100,Math.round((totalSave/totalGoal)*100)):0;
  $("goalMonthPct").textContent=monthPct+"%";$("goalTotalPct").textContent=totalPct+"%";$("goalMonthBar").style.width=monthPct+"%";$("goalTotalBar").style.width=totalPct+"%";
  $("goalMonthText").textContent=monthGoal?`${formatMoney(monthSave)} de ${formatMoney(monthGoal)}`:"Sin meta definida";$("goalTotalText").textContent=totalGoal?`${formatMoney(totalSave)} de ${formatMoney(totalGoal)}`:"Sin meta definida";
  $("monthSummary").textContent=buildMonthSummary(monthIncome,monthExpense,monthDebt,monthBalance);$("monthInsight").textContent=buildMonthInsight(monthRows);$("monthBudgetInfo").textContent=buildBudgetInfo(monthRows);
}
function renderBudgetList(){const list=$("budgetList");if(!state.budgets.length){list.innerHTML='<div class="empty">Aún no han definido presupuestos por categoría.</div>';return;}const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));list.innerHTML=state.budgets.map(b=>{const spent=monthMap[b.category]||0;const pct=b.amount?Math.round((spent/b.amount)*100):0;return `<div class="list-item"><div><strong>${b.category}</strong><div class="muted">Gastado este mes: ${formatMoney(spent)} / ${formatMoney(b.amount)}</div><div class="progress" style="margin-top:8px"><div style="width:${Math.min(100,pct)}%"></div></div></div><div class="stack"><span class="tag ${pct>100?'personal':'shared'}">${pct}%</span><button class="btn btn-outline" data-remove-budget="${b.id}">Eliminar</button></div></div>`;}).join("");
  list.querySelectorAll("[data-remove-budget]").forEach(btn=>btn.addEventListener("click",()=>{state.budgets=state.budgets.filter(b=>b.id!==btn.dataset.removeBudget);saveData(state);}));
}
function renderChart(){const area=$("chartArea"), rows=expenseByCategory(currentMonthRows());if(!rows.length){area.innerHTML='<div class="empty">Cuando registren gastos, aquí verán en qué se está yendo más el dinero.</div>';return;}const max=rows[0].amount||1;area.innerHTML=rows.slice(0,7).map(r=>`<div class="bar"><strong>${r.category}</strong><div class="bar-track"><div class="bar-fill" style="width:${Math.max(6,Math.round((r.amount/max)*100))}%"></div></div><div class="right">${formatMoney(r.amount)}</div></div>`).join("");}
function filteredTransactions(){const owner=$("filterOwner").value,type=$("filterType").value;return [...state.transactions].filter(t=>owner==="Todos"||t.owner===owner).filter(t=>type==="Todos"||t.type===type).sort((a,b)=>(b.date||"").localeCompare(a.date||""));}
function labelType(type){return type==="ingreso"?"Ingreso":type==="gasto"?"Gasto":"Deuda / cuota";}
function renderTransactions(){const tbody=$("txTable"), rows=filteredTransactions();if(!rows.length){tbody.innerHTML='<tr><td colspan="7">No hay movimientos registrados.</td></tr>';return;}tbody.innerHTML=rows.map(t=>`<tr><td>${t.date||""}</td><td>${labelType(t.type)}</td><td>${t.owner}</td><td>${t.category}</td><td>${t.description}</td><td class="right">${formatMoney(t.amount)}</td><td><button class="btn btn-outline" data-delete="${t.id}">Eliminar</button></td></tr>`).join("");tbody.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",()=>{state.transactions=state.transactions.filter(t=>t.id!==btn.dataset.delete);saveData(state);}));}
function renderReports(){$("reportAccounts").innerHTML=OWNERS.map(owner=>{const d=byOwner(owner);return `<div class="mini-card"><div class="section-title"><h3>${owner}</h3><span class="tag ${owner==="Hogar"?"shared":"personal"}">${owner==="Hogar"?"Compartido":"Personal"}</span></div><div class="kpi-row"><div><div class="muted">Ingresos</div><strong>${formatMoney(d.income)}</strong></div><div><div class="muted">Gastos</div><strong>${formatMoney(d.expense)}</strong></div><div><div class="muted">Deudas</div><strong>${formatMoney(d.debt)}</strong></div><div><div class="muted">Balance</div><strong>${formatMoney(d.balance)}</strong></div></div></div>`;}).join("");
  const alerts=getBudgetAlerts(), container=$("budgetAlerts");container.innerHTML=alerts.length?alerts.map(a=>`<div class="list-item"><div><strong>${a.category}</strong><div class="muted">Gastado: ${formatMoney(a.spent)} de ${formatMoney(a.limit)}</div></div><div class="stack"><span class="tag ${a.percent>100?'personal':'shared'}">${a.percent}%</span></div></div>`).join(""):'<div class="empty">No hay alertas. Todo va dentro del presupuesto configurado.</div>';
}
function renderRecent(){const list=$("recentList"), rows=[...state.transactions].sort((a,b)=>(b.date||"").localeCompare(a.date||"")).slice(0,5);list.innerHTML=rows.length?rows.map(t=>`<div class="list-item"><div><strong>${t.description}</strong><div class="muted">${t.date} · ${t.owner} · ${labelType(t.type)}</div></div><div class="${t.type==="ingreso"?"money positive":"money negative"}">${formatMoney(t.amount)}</div></div>`).join(""):'<div class="empty">Todavía no hay movimientos registrados.</div>';}
function updateLastSaved(){const el=$("lastSaved");if(!state.savedAt){el.textContent="Sin cambios guardados todavía.";return;}el.textContent="Último guardado: "+new Date(state.savedAt).toLocaleString("es-CO");}
function exportBackup(){downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),"backup-finanzas-alexander-nuri-v31.json");}
function importBackup(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{saveData(normalize(JSON.parse(reader.result)));alert("Backup importado correctamente.");event.target.value="";}catch{alert("El archivo no es válido.");}};reader.readAsText(file);}
function exportCSV(){const head=["fecha","tipo","responsable","categoria","descripcion","valor","metodo","nota","split","estado_deuda"];const rows=state.transactions.map(t=>[t.date,t.type,t.owner,t.category,t.description||"",t.amount,t.method,t.note||"",t.split,t.debtStatus]);const csv=[head.join(","),...rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","))].join("\n");downloadBlob(new Blob([csv],{type:"text/csv;charset=utf-8;"}),"movimientos-finanzas-alexander-nuri-v31.csv");}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function render(){$("goalMonthly").value=state.goals.monthly||"";$("goalTotal").value=state.goals.total||"";renderDashboard();renderBudgetList();renderChart();renderTransactions();renderReports();renderRecent();updateLastSaved();}
populateSelects();setTabs();setupEvents();clearTransactionForm();render();
