const STORAGE_KEY = "finanzas_familiares_v32_final";
const SESSION_KEY = "finanzas_familiares_v32_session";
const LEGACY_KEYS = ["finanzas_familiares_v31_premium","finanzas_familiares_v2_bonita","finanzas_familiares_v3_elegante","finanzas_familiares_v3","finanzas_familiares_v2","finanzas_familiares_v1"];
const OWNERS = ["Alexander","Nuri","Hogar"];
const CATEGORIES = ["Mercado","Servicios","Transporte","Salud","Educación","Ahorro","Entretenimiento","Arriendo","Cuotas","Deudas","Regalos","Otros"];
const APP_LOGIN = { user1:"Alexander", user2:"Nuri", pass:"hogar2026" };
const $ = (id) => document.getElementById(id);
let editingId = null;
const state = loadData();
function defaultState(){return {goals:{monthly:0,total:0},goalItems:[],budgets:[],transactions:[],savedAt:null};}
function normalize(data){const base=defaultState();return {goals:{...base.goals,...(data.goals||{})},goalItems:Array.isArray(data.goalItems)?data.goalItems:[],budgets:Array.isArray(data.budgets)?data.budgets:[],transactions:Array.isArray(data.transactions)?data.transactions:[],savedAt:data.savedAt||null};}
function loadData(){try{const current=localStorage.getItem(STORAGE_KEY);if(current)return normalize(JSON.parse(current));for(const key of LEGACY_KEYS){const legacy=localStorage.getItem(key);if(legacy){const parsed=normalize(JSON.parse(legacy));localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));return parsed;}}}catch(e){console.error(e);}return defaultState();}
function saveData(next=state){next.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state.goals=next.goals;state.goalItems=next.goalItems;state.budgets=next.budgets;state.transactions=next.transactions;state.savedAt=next.savedAt;render();}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);} function sum(arr){return arr.reduce((a,b)=>a+(Number(b)||0),0);} function formatMoney(n=0){return new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(n)||0);} function labelType(type){if(type==="ingreso")return "Ingreso";if(type==="gasto")return "Gasto";return "Deuda / cuota";}
function escapeHtml(str=""){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function setLogin(){const logged=sessionStorage.getItem(SESSION_KEY)==="ok";$("loginScreen").classList.toggle("hidden",logged);$("appScreen").classList.toggle("hidden",!logged);$("btnLogin").addEventListener("click",()=>{const user=($("loginUser").value||"").trim();const pass=($("loginPass").value||"").trim();if((user===APP_LOGIN.user1||user===APP_LOGIN.user2)&&pass===APP_LOGIN.pass){sessionStorage.setItem(SESSION_KEY,"ok");$("loginScreen").classList.add("hidden");$("appScreen").classList.remove("hidden");$("loginMsg").textContent="Acceso concedido.";}else{$("loginMsg").textContent="Usuario o clave incorrectos.";}});$("btnLogout").addEventListener("click",()=>{sessionStorage.removeItem(SESSION_KEY);location.reload();});}
function populateSelects(){[$("txCategory"),$("budgetCategory")].forEach(sel=>{sel.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join("");});$("txDate").value=new Date().toISOString().slice(0,10);}
function setTabs(){document.querySelectorAll(".tab").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const tab=btn.dataset.tab;document.querySelectorAll(".tab-content").forEach(sec=>sec.classList.add("hidden"));$("tab-"+tab).classList.remove("hidden");});});}
function setupEvents(){$("btnSaveTx").addEventListener("click",saveTransaction);$("btnClearTx").addEventListener("click",clearTransactionForm);$("btnSaveBudget").addEventListener("click",()=>{const category=$("budgetCategory").value;const amount=Number($("budgetAmount").value||0);if(!category||amount<=0)return alert("Ingresa una categoría y un monto válido.");const found=state.budgets.find(b=>b.category===category);if(found)found.amount=amount;else state.budgets.push({id:uid(),category,amount});$("budgetAmount").value="";saveData(state);});$("btnSaveGoalItem").addEventListener("click",()=>{const name=($("goalName").value||"").trim();const amount=Number($("goalAmount").value||0);const saved=Number($("goalSaved").value||0);const owner=$("goalOwner").value;if(!name||amount<=0)return alert("Ingresa un nombre y una meta válida.");state.goalItems.push({id:uid(),name,amount,saved,owner});$("goalName").value="";$("goalAmount").value="";$("goalSaved").value="";$("goalOwner").value="Hogar";saveData(state);});$("filterOwner").addEventListener("change",renderTransactions);$("filterType").addEventListener("change",renderTransactions);$("btnBackup").addEventListener("click",exportBackup);$("btnImport").addEventListener("click",()=>$("fileImport").click());$("fileImport").addEventListener("change",importBackup);$("btnExcel").addEventListener("click",exportCSV);$("btnReset").addEventListener("click",()=>{if(confirm("Esto reiniciará la app localmente. ¿Continuar?")){localStorage.removeItem(STORAGE_KEY);saveData(defaultState());clearTransactionForm();}});}
function getTotals(){const income=sum(state.transactions.filter(t=>t.type==="ingreso").map(t=>t.amount));const expense=sum(state.transactions.filter(t=>t.type==="gasto").map(t=>t.amount));const debt=sum(state.transactions.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));return {income,expense,debt,balance:income-expense-debt};}
function byOwner(owner){const rows=state.transactions.filter(t=>t.owner===owner);const income=sum(rows.filter(t=>t.type==="ingreso").map(t=>t.amount));const expense=sum(rows.filter(t=>t.type==="gasto").map(t=>t.amount));const debt=sum(rows.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));return {income,expense,debt,balance:income-expense-debt};}
function currentMonthRows(){const ym=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>(t.date||"").slice(0,7)===ym);}
function expenseByCategory(rows=state.transactions){const map={};rows.filter(t=>t.type==="gasto"||t.type==="deuda").forEach(t=>{map[t.category]=(map[t.category]||0)+Number(t.amount||0);});return Object.entries(map).map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);}
function getBudgetAlerts(){const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));return state.budgets.map(b=>{const spent=monthMap[b.category]||0;const percent=b.amount?Math.round((spent/b.amount)*100):0;return {category:b.category,spent,limit:b.amount,percent};}).filter(x=>x.percent>=80).sort((a,b)=>b.percent-a.percent);}
function recurringItems(){return state.transactions.filter(t=>t.recurring==="si");}
function saveTransaction(){const tx={id:editingId||uid(),type:$("txType").value,owner:$("txOwner").value,date:$("txDate").value||new Date().toISOString().slice(0,10),category:$("txCategory").value,amount:Number($("txAmount").value||0),method:$("txMethod").value,description:($("txDescription").value||"").trim(),note:($("txNote").value||"").trim(),split:$("txSplit").value,debtStatus:$("txDebtStatus").value,recurring:$("txRecurring").value};if(!tx.amount||tx.amount<=0||!tx.description){alert("Completa al menos valor y descripción.");return;}if(editingId){const idx=state.transactions.findIndex(t=>t.id===editingId);if(idx>=0)state.transactions[idx]=tx;editingId=null;clearTransactionForm(true);return saveData(state);}if(tx.type==="gasto"&&tx.split==="si"){const half=Math.round(tx.amount/2);const other=tx.amount-half;state.transactions.push({...tx,id:uid(),owner:"Alexander",amount:half,description:tx.description+" (50/50)"},{...tx,id:uid(),owner:"Nuri",amount:other,description:tx.description+" (50/50)"});}else{state.transactions.push(tx);}clearTransactionForm(true);saveData(state);}
function clearTransactionForm(keepBadge){$("txType").value="ingreso";$("txOwner").value="Alexander";$("txDate").value=new Date().toISOString().slice(0,10);$("txCategory").value=CATEGORIES[0];$("txAmount").value="";$("txMethod").value="Efectivo";$("txDescription").value="";$("txNote").value="";$("txSplit").value="no";$("txDebtStatus").value="pendiente";$("txRecurring").value="no";editingId=null;$("formTitle").textContent="Nuevo movimiento";$("editBadge").textContent=keepBadge?"Listo para guardar":"Formulario limpio";$("editBadge").className="tag shared";}
function editTransaction(id){const tx=state.transactions.find(t=>t.id===id);if(!tx)return;editingId=id;$("txType").value=tx.type;$("txOwner").value=tx.owner;$("txDate").value=tx.date||new Date().toISOString().slice(0,10);$("txCategory").value=tx.category;$("txAmount").value=tx.amount;$("txMethod").value=tx.method||"Efectivo";$("txDescription").value=tx.description||"";$("txNote").value=tx.note||"";$("txSplit").value=tx.split||"no";$("txDebtStatus").value=tx.debtStatus||"pendiente";$("txRecurring").value=tx.recurring||"no";$("formTitle").textContent="Editar movimiento";$("editBadge").textContent="Modo edición";$("editBadge").className="tag warn";document.querySelector('[data-tab="movimiento"]').click();}
function deleteTransaction(id){state.transactions=state.transactions.filter(t=>t.id!==id);saveData(state);} function removeBudget(id){state.budgets=state.budgets.filter(b=>b.id!==id);saveData(state);} function removeGoalItem(id){state.goalItems=state.goalItems.filter(g=>g.id!==id);saveData(state);}
function setProgressClass(id,mode){const el=$(id);el.className="progress"+(mode?" "+mode:"");}
function computeBudgetStatus(){const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));if(!state.budgets.length)return {percent:0,text:"Todavía no hay presupuesto configurado."};const totalLimit=sum(state.budgets.map(b=>b.amount));const totalSpent=sum(state.budgets.map(b=>monthMap[b.category]||0));const percent=totalLimit?Math.round((totalSpent/totalLimit)*100):0;let text=`Gastado ${formatMoney(totalSpent)} de ${formatMoney(totalLimit)}.`;if(percent>100)text+=" Ya pasaron el límite mensual.";else if(percent>=80)text+=" Ojo: están cerca del tope.";else text+=" Van dentro del rango previsto.";return {percent,text};}
function buildMonthSummary(income,expense,debt,balance){if(!currentMonthRows().length)return "Todavía no hay suficientes movimientos para el cierre mensual.";if(balance>=0)return `Este mes cerraron con saldo positivo de ${formatMoney(balance)}. Van por buen camino.`;return `Este mes cerraron con un faltante de ${formatMoney(Math.abs(balance))}. Conviene ajustar algunos gastos.`;}
function buildMonthInsight(rows){if(!rows.length)return "Empiecen registrando movimientos para ver recomendaciones.";const activeOwner=OWNERS.map(o=>({owner:o,total:sum(rows.filter(t=>t.owner===o).map(t=>t.amount))})).sort((a,b)=>b.total-a.total)[0];const topCategory=expenseByCategory(rows)[0];if(!topCategory)return `La cuenta más activa fue ${activeOwner.owner}.`;return `La cuenta más activa fue ${activeOwner.owner} y la categoría dominante fue ${topCategory.category}.`;}
function buildBudgetInfo(rows){if(!rows.length)return "Aún no hay datos para comparar.";const alerts=getBudgetAlerts();if(!alerts.length)return "Van dentro del presupuesto en las categorías configuradas.";const worst=alerts[0];if(worst.percent>100)return `La categoría ${worst.category} ya superó el presupuesto con ${worst.percent}%.`;return `La categoría ${worst.category} va en ${worst.percent}% del presupuesto mensual.`;}
function renderDashboard(){const totals=getTotals();$("metricBalance").textContent=formatMoney(totals.balance);$("metricIncome").textContent=formatMoney(totals.income);$("metricExpense").textContent=formatMoney(totals.expense);$("metricDebt").textContent=formatMoney(totals.debt);OWNERS.forEach(owner=>{const key=owner==="Hogar"?"Hogar":owner;const info=byOwner(owner);$("sum"+key+"Income").textContent=formatMoney(info.income);$("sum"+key+"Expense").textContent=formatMoney(info.expense);$("sum"+key+"Debt").textContent=formatMoney(info.debt);$("sum"+key+"Balance").textContent=formatMoney(info.balance);});const monthRows=currentMonthRows();const monthIncome=sum(monthRows.filter(t=>t.type==="ingreso").map(t=>t.amount));const monthExpense=sum(monthRows.filter(t=>t.type==="gasto").map(t=>t.amount));const monthDebt=sum(monthRows.filter(t=>t.type==="deuda"&&t.debtStatus!=="pagada").map(t=>t.amount));const monthBalance=monthIncome-monthExpense-monthDebt;$("monthIncome").textContent=formatMoney(monthIncome);$("monthExpense").textContent=formatMoney(monthExpense+monthDebt);$("monthBalance").textContent=formatMoney(monthBalance);const monthlyGoal=Number(state.goals.monthly||0);const totalGoal=Number(state.goals.total||0);const monthlySavings=Math.max(0,monthBalance);const accumulatedSavings=Math.max(0,totals.balance);const monthPct=monthlyGoal>0?Math.min(100,Math.round((monthlySavings/monthlyGoal)*100)):0;const totalPct=totalGoal>0?Math.min(100,Math.round((accumulatedSavings/totalGoal)*100)):0;$("goalMonthPct").textContent=monthPct+"%";$("goalTotalPct").textContent=totalPct+"%";$("goalMonthBar").style.width=monthPct+"%";$("goalTotalBar").style.width=totalPct+"%";$("goalMonthText").textContent=monthlyGoal?`${formatMoney(monthlySavings)} de ${formatMoney(monthlyGoal)}`:"Sin meta definida";$("goalTotalText").textContent=totalGoal?`${formatMoney(accumulatedSavings)} de ${formatMoney(totalGoal)}`:"Sin meta definida";const budgetStatus=computeBudgetStatus();$("budgetStatusLabel").textContent=budgetStatus.percent+"%";$("budgetStatusBar").style.width=Math.min(100,budgetStatus.percent)+"%";$("budgetStatusText").textContent=budgetStatus.text;setProgressClass("goalMonthWrap",monthPct>=100?"good":monthPct>=70?"warn":"");setProgressClass("goalTotalWrap",totalPct>=100?"good":totalPct>=70?"warn":"");setProgressClass("budgetStatusWrap",budgetStatus.percent>100?"danger":budgetStatus.percent>=80?"warn":"good");$("monthSummary").textContent=buildMonthSummary(monthIncome,monthExpense,monthDebt,monthBalance);$("monthInsight").textContent=buildMonthInsight(monthRows);$("monthBudgetInfo").textContent=buildBudgetInfo(monthRows);}
function renderBudgetList(){const list=$("budgetList");if(!state.budgets.length){list.innerHTML='<div class="empty">Aún no han definido presupuestos por categoría.</div>';return;}const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));list.innerHTML=state.budgets.map(b=>{const spent=monthMap[b.category]||0;const pct=b.amount?Math.round((spent/b.amount)*100):0;const klass=pct>100?"alert":pct>=80?"warn":"shared";const progressClass=pct>100?"danger":pct>=80?"warn":"good";return `<div class="list-item"><div style="flex:1"><strong>${escapeHtml(b.category)}</strong><div class="muted">Gastado este mes: ${formatMoney(spent)} / ${formatMoney(b.amount)}</div><div class="progress ${progressClass}" style="margin-top:8px"><div style="width:${Math.min(100,pct)}%"></div></div></div><div class="stack"><span class="tag ${klass}">${pct}%</span><button class="btn btn-outline icon-btn" data-remove-budget="${b.id}">Eliminar</button></div></div>`;}).join("");list.querySelectorAll("[data-remove-budget]").forEach(btn=>btn.addEventListener("click",()=>removeBudget(btn.dataset.removeBudget)));}
function renderGoals(){const totalGoalAmount=sum(state.goalItems.map(g=>g.amount));if(!state.goals.total&&totalGoalAmount)state.goals.total=totalGoalAmount;const list=$("goalList");if(!state.goalItems.length){list.innerHTML='<div class="empty">Todavía no han creado metas por objetivo.</div>';return;}list.innerHTML=state.goalItems.map(g=>{const pct=g.amount?Math.min(100,Math.round((g.saved/g.amount)*100)):0;const mode=pct>=100?"good":pct>=70?"warn":"";return `<div class="list-item"><div style="flex:1"><strong>${escapeHtml(g.name)}</strong><div class="muted">${escapeHtml(g.owner)} · ${formatMoney(g.saved)} de ${formatMoney(g.amount)}</div><div class="progress ${mode}" style="margin-top:8px"><div style="width:${pct}%"></div></div></div><div class="stack"><span class="tag ${pct>=100?"shared":"personal"}">${pct}%</span><button class="btn btn-outline icon-btn" data-remove-goal="${g.id}">Eliminar</button></div></div>`;}).join("");list.querySelectorAll("[data-remove-goal]").forEach(btn=>btn.addEventListener("click",()=>removeGoalItem(btn.dataset.removeGoal)));state.goals.total=totalGoalAmount||state.goals.total;}
function renderChart(){const area=$("chartArea");const rows=expenseByCategory(currentMonthRows());if(!rows.length){area.innerHTML='<div class="empty">Cuando registren gastos, aquí verán en qué se está yendo más el dinero.</div>';return;}const max=rows[0].amount||1;area.innerHTML=rows.slice(0,7).map(r=>`<div class="bar"><strong>${escapeHtml(r.category)}</strong><div class="bar-track"><div class="bar-fill" style="width:${Math.max(6,Math.round((r.amount/max)*100))}%"></div></div><div class="right">${formatMoney(r.amount)}</div></div>`).join("");}
function renderRecurring(){const list=$("recurringList");const items=recurringItems();if(!items.length){list.innerHTML='<div class="empty">Aquí aparecerán las cuotas o pagos marcados como recurrentes mensuales.</div>';return;}list.innerHTML=items.map(t=>`<div class="list-item"><div><strong>${escapeHtml(t.description)}</strong><div class="muted">${escapeHtml(t.owner)} · ${escapeHtml(labelType(t.type))} · ${formatMoney(t.amount)}</div></div><div class="stack"><span class="tag warn">Mensual</span></div></div>`).join("");}
function filteredTransactions(){const owner=$("filterOwner").value;const type=$("filterType").value;return [...state.transactions].filter(t=>owner==="Todos"?true:t.owner===owner).filter(t=>type==="Todos"?true:t.type===type).sort((a,b)=>(b.date||"").localeCompare(a.date||""));}
function renderTransactions(){const tbody=$("txTable");const rows=filteredTransactions();if(!rows.length){tbody.innerHTML='<tr><td colspan="7">No hay movimientos registrados.</td></tr>';return;}tbody.innerHTML=rows.map(t=>`<tr><td>${escapeHtml(t.date||"")}</td><td>${escapeHtml(labelType(t.type))}</td><td>${escapeHtml(t.owner)}</td><td>${escapeHtml(t.category)}</td><td>${escapeHtml(t.description)}</td><td class="right">${formatMoney(t.amount)}</td><td><div class="stack"><button class="btn btn-outline icon-btn" data-edit="${t.id}">Editar</button><button class="btn btn-danger icon-btn" data-delete="${t.id}">Borrar</button></div></td></tr>`).join("");tbody.querySelectorAll("[data-edit]").forEach(btn=>btn.addEventListener("click",()=>editTransaction(btn.dataset.edit)));tbody.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",()=>deleteTransaction(btn.dataset.delete)));}
function renderReports(){$("reportAccounts").innerHTML=OWNERS.map(owner=>{const d=byOwner(owner);return `<div class="mini-card"><div class="section-title"><h3>${escapeHtml(owner)}</h3><span class="tag ${owner==="Hogar"?"shared":"personal"}">${owner==="Hogar"?"Compartido":"Personal"}</span></div><div class="kpi-row"><div><div class="muted">Ingresos</div><strong>${formatMoney(d.income)}</strong></div><div><div class="muted">Gastos</div><strong>${formatMoney(d.expense)}</strong></div><div><div class="muted">Deudas</div><strong>${formatMoney(d.debt)}</strong></div><div><div class="muted">Balance</div><strong>${formatMoney(d.balance)}</strong></div></div></div>`;}).join("");const alerts=getBudgetAlerts();const container=$("budgetAlerts");if(!alerts.length){container.innerHTML='<div class="empty">No hay alertas. Todo va dentro del presupuesto configurado.</div>';return;}container.innerHTML=alerts.map(a=>`<div class="list-item"><div><strong>${escapeHtml(a.category)}</strong><div class="muted">Gastado: ${formatMoney(a.spent)} de ${formatMoney(a.limit)}</div></div><div class="stack"><span class="tag ${a.percent>100?"alert":"warn"}">${a.percent}%</span></div></div>`).join("");}
function renderRecent(){const list=$("recentList");const rows=[...state.transactions].sort((a,b)=>(b.date||"").localeCompare(a.date||"")).slice(0,5);if(!rows.length){list.innerHTML='<div class="empty">Todavía no hay movimientos registrados.</div>';return;}list.innerHTML=rows.map(t=>`<div class="list-item"><div><strong>${escapeHtml(t.description)}</strong><div class="muted">${escapeHtml(t.date)} · ${escapeHtml(t.owner)} · ${escapeHtml(labelType(t.type))}${t.recurring==="si"?" · mensual":""}</div></div><div class="${t.type==="ingreso"?"money positive":"money negative"}">${formatMoney(t.amount)}</div></div>`).join("");}
function updateLastSaved(){const el=$("lastSaved");if(!state.savedAt){el.textContent="Sin cambios guardados todavía.";return;}el.textContent="Último guardado: "+new Date(state.savedAt).toLocaleString("es-CO");}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});downloadBlob(blob,"backup-finanzas-alexander-nuri-v32.json");}
function importBackup(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=normalize(JSON.parse(reader.result));saveData(parsed);alert("Backup importado correctamente.");event.target.value="";}catch{alert("El archivo no es válido.");}};reader.readAsText(file);}
function exportCSV(){const header=["fecha","tipo","responsable","categoria","descripcion","valor","metodo","nota","split","estado_deuda","recurrente"];const rows=state.transactions.map(t=>[t.date,t.type,t.owner,t.category,t.description||"",t.amount,t.method,t.note||"",t.split,t.debtStatus,t.recurring]);const csv=[header.join(","),...rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(","))].join("\n");downloadBlob(new Blob([csv],{type:"text/csv;charset=utf-8;"}),"movimientos-finanzas-alexander-nuri-v32.csv");}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function render(){renderGoals();renderDashboard();renderBudgetList();renderChart();renderRecurring();renderTransactions();renderReports();renderRecent();updateLastSaved();}
populateSelects();setTabs();setLogin();setupEvents();clearTransactionForm();render();
