const STORAGE_KEY='finanzas_familiares_v34_ejecutiva';
const SESSION_KEY='finanzas_familiares_v34_session';
const LEGACY_KEYS=['finanzas_familiares_v33_flujo','finanzas_familiares_v32_final','finanzas_familiares_v31_premium','finanzas_familiares_v3_elegante','finanzas_familiares_v2_bonita','finanzas_familiares_v2','finanzas_familiares_v1'];
const LOGIN={users:['Alexander','Nuri'],pass:'hogar2026'};
const OWNERS=['Alexander','Nuri','Hogar'];
const INCOME_CATEGORIES=['Salario','Prima','Bono','Honorarios','Comisiones','Aporte al hogar','Reembolso','Otros ingresos'];
const EXPENSE_CATEGORIES=['Mercado','Servicios','Transporte','Salud','Educación','Arriendo','Entretenimiento','Regalos','Mascotas','Otros'];
const DEBT_CATEGORIES=['Tarjeta de crédito','Préstamo','Cuota hogar','Crédito','Deuda personal','Otros'];
const $=id=>document.getElementById(id);
let editingId=null, editingMode='income';
const state=loadData();
function defaultState(){return{goals:{monthly:0,total:0},goalItems:[],budgets:[],transactions:[],savedAt:null};}
function normalize(data){const base=defaultState();return{goals:{...base.goals,...(data.goals||{})},goalItems:Array.isArray(data.goalItems)?data.goalItems:[],budgets:Array.isArray(data.budgets)?data.budgets:[],transactions:Array.isArray(data.transactions)?data.transactions:[],savedAt:data.savedAt||null};}
function loadData(){try{const current=localStorage.getItem(STORAGE_KEY);if(current)return normalize(JSON.parse(current));for(const key of LEGACY_KEYS){const legacy=localStorage.getItem(key);if(legacy){const parsed=normalize(JSON.parse(legacy));localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));return parsed;}}}catch(e){console.error(e);}return defaultState();}
function saveData(next=state){next.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state.goals=next.goals;state.goalItems=next.goalItems;state.budgets=next.budgets;state.transactions=next.transactions;state.savedAt=next.savedAt;render();}
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const sum=arr=>arr.reduce((a,b)=>a+(Number(b)||0),0);
const fmt=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const labelType=t=>t==='ingreso'?'Ingreso':t==='gasto'?'Gasto':'Deuda / cuota';
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function setLogin(){const logged=sessionStorage.getItem(SESSION_KEY)==='ok';$('loginScreen').classList.toggle('hidden',logged);$('appScreen').classList.toggle('hidden',!logged);$('btnLogin').addEventListener('click',()=>{const user=($('loginUser').value||'').trim();const pass=($('loginPass').value||'').trim();if(LOGIN.users.includes(user)&&pass===LOGIN.pass){sessionStorage.setItem(SESSION_KEY,'ok');$('loginScreen').classList.add('hidden');$('appScreen').classList.remove('hidden');}else{$('loginMsg').textContent='Usuario o clave incorrectos.';}});$('btnLogout').addEventListener('click',()=>{sessionStorage.removeItem(SESSION_KEY);location.reload();});}
function populateSelects(){$('incomeCategory').innerHTML=INCOME_CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('expenseCategory').innerHTML=EXPENSE_CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('budgetCategory').innerHTML=EXPENSE_CATEGORIES.map(c=>`<option>${c}</option>`).join('');const today=new Date().toISOString().slice(0,10);$('incomeDate').value=today;$('expenseDate').value=today;}
function setTabs(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const tab=btn.dataset.tab;document.querySelectorAll('.tab-content').forEach(sec=>sec.classList.add('hidden'));$('tab-'+tab).classList.remove('hidden');}));}
function setupEvents(){$('btnSaveIncome').addEventListener('click',saveIncome);$('btnClearIncome').addEventListener('click',()=>clearIncomeForm(true));$('btnSaveExpense').addEventListener('click',saveExpense);$('btnClearExpense').addEventListener('click',()=>clearExpenseForm(true));$('expenseType').addEventListener('change',updateExpenseCategories);$('btnSaveBudget').addEventListener('click',saveBudget);$('btnSaveGoalItem').addEventListener('click',saveGoalItem);$('filterOwner').addEventListener('change',renderTransactions);$('filterType').addEventListener('change',renderTransactions);$('btnBackup').addEventListener('click',exportBackup);$('btnImport').addEventListener('click',()=>$('fileImport').click());$('fileImport').addEventListener('change',importBackup);$('btnExcel').addEventListener('click',exportCSV);$('btnReset').addEventListener('click',()=>{if(confirm('Esto reiniciará la app localmente. ¿Continuar?')){localStorage.removeItem(STORAGE_KEY);saveData(defaultState());clearIncomeForm();clearExpenseForm();}});}
function updateExpenseCategories(){const list=$('expenseType').value==='deuda'?DEBT_CATEGORIES:EXPENSE_CATEGORIES;$('expenseCategory').innerHTML=list.map(c=>`<option>${c}</option>`).join('');}
function saveIncome(){const tx={id:editingMode==='income'&&editingId?editingId:uid(),type:'ingreso',owner:$('incomeOwner').value,date:$('incomeDate').value||new Date().toISOString().slice(0,10),category:$('incomeCategory').value,amount:Number($('incomeAmount').value||0),method:$('incomeMethod').value,description:($('incomeDescription').value||'').trim(),note:($('incomeNote').value||'').trim(),split:'no',debtStatus:'pagada',recurring:'no'};if(!tx.amount||!tx.description)return alert('Completa al menos valor y descripción.');if(editingMode==='income'&&editingId){const idx=state.transactions.findIndex(t=>t.id===editingId);if(idx>=0)state.transactions[idx]=tx;editingId=null;clearIncomeForm();return saveData(state);}state.transactions.push(tx);clearIncomeForm();saveData(state);}
function saveExpense(){const tx={id:editingMode==='expense'&&editingId?editingId:uid(),type:$('expenseType').value,owner:$('expenseOwner').value,date:$('expenseDate').value||new Date().toISOString().slice(0,10),category:$('expenseCategory').value,amount:Number($('expenseAmount').value||0),method:$('expenseMethod').value,description:($('expenseDescription').value||'').trim(),note:($('expenseNote').value||'').trim(),split:$('expenseSplit').value,debtStatus:$('expenseDebtStatus').value,recurring:$('expenseRecurring').value};if(!tx.amount||!tx.description)return alert('Completa al menos valor y descripción.');if(editingMode==='expense'&&editingId){const idx=state.transactions.findIndex(t=>t.id===editingId);if(idx>=0)state.transactions[idx]=tx;editingId=null;clearExpenseForm();return saveData(state);}if(tx.type==='gasto'&&tx.split==='si'){const half=Math.round(tx.amount/2),other=tx.amount-half;state.transactions.push({...tx,id:uid(),owner:'Alexander',amount:half,description:tx.description+' (50/50)'},{...tx,id:uid(),owner:'Nuri',amount:other,description:tx.description+' (50/50)'});}else state.transactions.push(tx);clearExpenseForm();saveData(state);}
function clearIncomeForm(resetBadge){$('incomeOwner').value='Alexander';$('incomeDate').value=new Date().toISOString().slice(0,10);$('incomeCategory').value='Salario';$('incomeAmount').value='';$('incomeMethod').value='Efectivo';$('incomeDescription').value='';$('incomeNote').value='';editingMode='income';editingId=null;$('incomeFormTitle').textContent='Nuevo ingreso';$('incomeEditBadge').textContent=resetBadge?'Ingreso':'Listo';$('incomeEditBadge').className='tag personal';}
function clearExpenseForm(resetBadge){$('expenseType').value='gasto';updateExpenseCategories();$('expenseOwner').value='Hogar';$('expenseDate').value=new Date().toISOString().slice(0,10);$('expenseCategory').value=EXPENSE_CATEGORIES[0];$('expenseAmount').value='';$('expenseMethod').value='Efectivo';$('expenseDescription').value='';$('expenseNote').value='';$('expenseSplit').value='no';$('expenseDebtStatus').value='pendiente';$('expenseRecurring').value='no';editingMode='expense';editingId=null;$('expenseFormTitle').textContent='Nuevo gasto o deuda';$('expenseEditBadge').textContent=resetBadge?'Gasto':'Listo';$('expenseEditBadge').className='tag warn';}
function saveBudget(){const category=$('budgetCategory').value,amount=Number($('budgetAmount').value||0);if(!category||amount<=0)return alert('Ingresa una categoría y un monto válido.');const found=state.budgets.find(b=>b.category===category);if(found)found.amount=amount;else state.budgets.push({id:uid(),category,amount});$('budgetAmount').value='';saveData(state);}
function saveGoalItem(){const name=($('goalName').value||'').trim(),amount=Number($('goalAmount').value||0),saved=Number($('goalSaved').value||0),owner=$('goalOwner').value,monthly=Number($('goalMonthly').value||0);if(monthly>0)state.goals.monthly=monthly;if(!name||amount<=0){saveData(state);return;}state.goalItems.push({id:uid(),name,amount,saved,owner});$('goalName').value='';$('goalAmount').value='';$('goalSaved').value='';$('goalOwner').value='Hogar';saveData(state);}
function currentMonthRows(){const ym=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>(t.date||'').slice(0,7)===ym);}
function totals(){const income=sum(state.transactions.filter(t=>t.type==='ingreso').map(t=>t.amount));const expense=sum(state.transactions.filter(t=>t.type==='gasto').map(t=>t.amount));const debt=sum(state.transactions.filter(t=>t.type==='deuda'&&t.debtStatus!=='pagada').map(t=>t.amount));return{income,expense,debt,balance:income-expense-debt};}
function byOwner(owner){const rows=state.transactions.filter(t=>t.owner===owner);const income=sum(rows.filter(t=>t.type==='ingreso').map(t=>t.amount));const expense=sum(rows.filter(t=>t.type==='gasto').map(t=>t.amount));const debt=sum(rows.filter(t=>t.type==='deuda'&&t.debtStatus!=='pagada').map(t=>t.amount));return{income,expense,debt,balance:income-expense-debt};}
function expenseByCategory(rows=state.transactions){const map={};rows.filter(t=>t.type==='gasto'||t.type==='deuda').forEach(t=>{map[t.category]=(map[t.category]||0)+Number(t.amount||0);});return Object.entries(map).map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);}
function getBudgetAlerts(){const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));return state.budgets.map(b=>{const spent=monthMap[b.category]||0;const percent=b.amount?Math.round((spent/b.amount)*100):0;return{category:b.category,spent,limit:b.amount,percent};}).filter(x=>x.percent>=80).sort((a,b)=>b.percent-a.percent);}
function recurringItems(){return state.transactions.filter(t=>t.recurring==='si');}
function setProgressClass(id,mode){const el=$(id);el.className='progress'+(mode?' '+mode:'');}
function computeBudgetStatus(){const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));if(!state.budgets.length)return{percent:0,text:'Todavía no hay presupuesto configurado.'};const totalLimit=sum(state.budgets.map(b=>b.amount));const totalSpent=sum(state.budgets.map(b=>monthMap[b.category]||0));const percent=totalLimit?Math.round((totalSpent/totalLimit)*100):0;let text=`Gastado ${fmt(totalSpent)} de ${fmt(totalLimit)}.`;if(percent>100)text+=' Ya pasaron el límite mensual.';else if(percent>=80)text+=' Ojo: están cerca del tope.';else text+=' Van dentro del rango previsto.';return{percent,text};}
function buildMonthSummary(income,expense,debt,balance){if(!currentMonthRows().length)return 'Todavía no hay suficientes movimientos para el cierre mensual.';if(balance>=0)return `Este mes cerraron con saldo positivo de ${fmt(balance)}.`;return `Este mes cerraron con un faltante de ${fmt(Math.abs(balance))}.`;}
function renderDashboard(){const all=totals();$('metricBalance').textContent=fmt(all.balance);const monthRows=currentMonthRows();const monthIncome=sum(monthRows.filter(t=>t.type==='ingreso').map(t=>t.amount));const monthExpense=sum(monthRows.filter(t=>t.type==='gasto').map(t=>t.amount));const monthDebt=sum(monthRows.filter(t=>t.type==='deuda'&&t.debtStatus!=='pagada').map(t=>t.amount));const monthBalance=monthIncome-monthExpense-monthDebt;$('monthIncome').textContent=fmt(monthIncome);$('monthExpense').textContent=fmt(monthExpense+monthDebt);$('monthBalance').textContent=fmt(monthBalance);const monthGoal=Number(state.goals.monthly||0),monthSave=Math.max(0,monthBalance),monthPct=monthGoal>0?Math.min(100,Math.round((monthSave/monthGoal)*100)):0;$('goalMonthPct').textContent=monthPct+'%';$('goalMonthBar').style.width=monthPct+'%';$('goalMonthText').textContent=monthGoal?`${fmt(monthSave)} de ${fmt(monthGoal)}`:'Sin meta definida';setProgressClass('goalMonthWrap',monthPct>=100?'good':monthPct>=70?'warn':'');const budget=computeBudgetStatus();$('budgetStatusLabel').textContent=budget.percent+'%';$('budgetStatusBar').style.width=Math.min(100,budget.percent)+'%';$('budgetStatusText').textContent=budget.text;setProgressClass('budgetStatusWrap',budget.percent>100?'danger':budget.percent>=80?'warn':'good');$('monthSummary').textContent=buildMonthSummary(monthIncome,monthExpense,monthDebt,monthBalance);}
function renderRecent(){const list=$('recentList');const rows=[...state.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5);if(!rows.length){list.innerHTML='<div class="empty">Todavía no hay movimientos registrados.</div>';return;}list.innerHTML=rows.map(t=>`<div class="list-item"><div><strong>${esc(t.description)}</strong><div class="muted">${esc(t.date)} · ${esc(t.owner)} · ${esc(labelType(t.type))}</div></div><div class="${t.type==='ingreso'?'money positive':'money negative'}">${fmt(t.amount)}</div></div>`).join('');}
function summaryBlock(owner,d){return `<div class="summary-row"><div><div class="summary-name">${esc(owner)}</div><div class="muted">${owner==='Hogar'?'Cuenta compartida del hogar':'Cuenta personal'}</div></div><div class="summary-grid"><div class="summary-cell"><div class="muted">Ingresos</div><strong>${fmt(d.income)}</strong></div><div class="summary-cell"><div class="muted">Gastos</div><strong>${fmt(d.expense)}</strong></div><div class="summary-cell"><div class="muted">Deudas</div><strong>${fmt(d.debt)}</strong></div><div class="summary-cell"><div class="muted">Balance</div><strong>${fmt(d.balance)}</strong></div></div></div>`;}
function renderIncomeSummary(){$('incomeSummary').innerHTML=OWNERS.map(owner=>summaryBlock(owner,byOwner(owner))).join('');}
function renderBudgetList(){const list=$('budgetList');if(!state.budgets.length){list.innerHTML='<div class="empty">Aún no han definido presupuestos por categoría.</div>';return;}const monthMap=Object.fromEntries(expenseByCategory(currentMonthRows()).map(x=>[x.category,x.amount]));list.innerHTML=state.budgets.map(b=>{const spent=monthMap[b.category]||0;const pct=b.amount?Math.round((spent/b.amount)*100):0;const klass=pct>100?'alert':pct>=80?'warn':'shared';const progress=pct>100?'danger':pct>=80?'warn':'good';return `<div class="list-item"><div style="flex:1"><strong>${esc(b.category)}</strong><div class="muted">Gastado este mes: ${fmt(spent)} / ${fmt(b.amount)}</div><div class="progress ${progress}" style="margin-top:8px"><div style="width:${Math.min(100,pct)}%"></div></div></div><div><span class="tag ${klass}">${pct}%</span></div></div>`;}).join('');}
function renderGoals(){if(state.goalItems.length){state.goals.total=sum(state.goalItems.map(g=>g.amount));}$('goalMonthly').value=state.goals.monthly||'';const list=$('goalList');if(!state.goalItems.length){list.innerHTML='<div class="empty">Todavía no han creado metas por objetivo.</div>';return;}list.innerHTML=state.goalItems.map(g=>{const pct=g.amount?Math.min(100,Math.round((g.saved/g.amount)*100)):0;const mode=pct>=100?'good':pct>=70?'warn':'';return `<div class="list-item"><div style="flex:1"><strong>${esc(g.name)}</strong><div class="muted">${esc(g.owner)} · ${fmt(g.saved)} de ${fmt(g.amount)}</div><div class="progress ${mode}" style="margin-top:8px"><div style="width:${pct}%"></div></div></div><div><span class="tag ${pct>=100?'shared':'personal'}">${pct}%</span></div></div>`;}).join('');}
function renderChart(){const area=$('chartArea');const rows=expenseByCategory(currentMonthRows());if(!rows.length){area.innerHTML='<div class="empty">Cuando registren gastos, aquí verán en qué se está yendo más el dinero.</div>';return;}const max=rows[0].amount||1;area.innerHTML=rows.slice(0,7).map(r=>`<div class="bar"><strong>${esc(r.category)}</strong><div class="bar-track"><div class="bar-fill" style="width:${Math.max(6,Math.round((r.amount/max)*100))}%"></div></div><div class="right">${fmt(r.amount)}</div></div>`).join('');}
function renderRecurring(){const list=$('recurringList');const items=recurringItems();if(!items.length){list.innerHTML='<div class="empty">Aquí aparecerán las cuotas o pagos marcados como recurrentes mensuales.</div>';return;}list.innerHTML=items.map(t=>`<div class="list-item"><div><strong>${esc(t.description)}</strong><div class="muted">${esc(t.owner)} · ${esc(labelType(t.type))} · ${fmt(t.amount)}</div></div><span class="tag warn">Mensual</span></div>`).join('');}
function filteredTransactions(){const owner=$('filterOwner').value,type=$('filterType').value;return [...state.transactions].filter(t=>owner==='Todos'||t.owner===owner).filter(t=>type==='Todos'||t.type===type).sort((a,b)=>(b.date||'').localeCompare(a.date||''));}
function editTransaction(id){const tx=state.transactions.find(t=>t.id===id);if(!tx)return;editingId=id;if(tx.type==='ingreso'){editingMode='income';$('incomeOwner').value=tx.owner;$('incomeDate').value=tx.date||new Date().toISOString().slice(0,10);$('incomeCategory').value=tx.category;$('incomeAmount').value=tx.amount;$('incomeMethod').value=tx.method||'Efectivo';$('incomeDescription').value=tx.description||'';$('incomeNote').value=tx.note||'';$('incomeFormTitle').textContent='Editar ingreso';$('incomeEditBadge').textContent='Modo edición';$('incomeEditBadge').className='tag warn';document.querySelector('[data-tab="ingresos"]').click();}else{editingMode='expense';$('expenseType').value=tx.type;updateExpenseCategories();$('expenseOwner').value=tx.owner;$('expenseDate').value=tx.date||new Date().toISOString().slice(0,10);$('expenseCategory').value=tx.category;$('expenseAmount').value=tx.amount;$('expenseMethod').value=tx.method||'Efectivo';$('expenseDescription').value=tx.description||'';$('expenseNote').value=tx.note||'';$('expenseSplit').value=tx.split||'no';$('expenseDebtStatus').value=tx.debtStatus||'pendiente';$('expenseRecurring').value=tx.recurring||'no';$('expenseFormTitle').textContent='Editar gasto o deuda';$('expenseEditBadge').textContent='Modo edición';$('expenseEditBadge').className='tag alert';document.querySelector('[data-tab="gastos"]').click();}}
function renderTransactions(){const tbody=$('txTable');const rows=filteredTransactions();if(!rows.length){tbody.innerHTML='<tr><td colspan="7">No hay movimientos registrados.</td></tr>';return;}tbody.innerHTML=rows.map(t=>`<tr><td>${esc(t.date||'')}</td><td>${esc(labelType(t.type))}</td><td>${esc(t.owner)}</td><td>${esc(t.category)}</td><td>${esc(t.description)}</td><td class="right">${fmt(t.amount)}</td><td><div class="actions" style="margin-top:0"><button class="btn btn-outline" data-edit="${t.id}">Editar</button><button class="btn btn-danger" data-delete="${t.id}">Borrar</button></div></td></tr>`).join('');tbody.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>editTransaction(btn.dataset.edit)));tbody.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>{state.transactions=state.transactions.filter(t=>t.id!==btn.dataset.delete);saveData(state);}));}
function renderReports(){$('reportAccounts').innerHTML=OWNERS.map(owner=>summaryBlock(owner,byOwner(owner))).join('');const alerts=getBudgetAlerts(),container=$('budgetAlerts');if(!alerts.length){container.innerHTML='<div class="empty">No hay alertas. Todo va dentro del presupuesto configurado.</div>';return;}container.innerHTML=alerts.map(a=>`<div class="list-item"><div><strong>${esc(a.category)}</strong><div class="muted">Gastado: ${fmt(a.spent)} de ${fmt(a.limit)}</div></div><span class="tag ${a.percent>100?'alert':'warn'}">${a.percent}%</span></div>`).join('');}
function updateLastSaved(){const el=$('lastSaved');el.textContent=state.savedAt?'Último guardado: '+new Date(state.savedAt).toLocaleString('es-CO'):'Sin cambios guardados todavía.';}
function exportBackup(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'backup-finanzas-v34-ejecutiva.json');}
function importBackup(ev){const file=ev.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{saveData(normalize(JSON.parse(r.result)));alert('Backup importado correctamente.');ev.target.value='';}catch{alert('El archivo no es válido.');}};r.readAsText(file);}
function exportCSV(){const header=['fecha','tipo','responsable','categoria','descripcion','valor','metodo','nota','split','estado_deuda','recurrente'];const rows=state.transactions.map(t=>[t.date,t.type,t.owner,t.category,t.description||'',t.amount,t.method,t.note||'',t.split,t.debtStatus,t.recurring]);const csv=[header.join(','),...rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','))].join('\n');download(new Blob([csv],{type:'text/csv;charset=utf-8;'}),'movimientos-finanzas-v34-ejecutiva.csv');}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function render(){renderDashboard();renderRecent();renderIncomeSummary();renderBudgetList();renderGoals();renderChart();renderRecurring();renderTransactions();renderReports();updateLastSaved();}
populateSelects();updateExpenseCategories();setTabs();setLogin();setupEvents();clearIncomeForm();clearExpenseForm();render();